export type PelotonWorkoutList = {
  data: [
    {
      created: number;
      created_at: number;
      device_time_created_at: number;
      device_type: string;
      effort_zones: any;
      end_time: number;
      fitbit_id: number;
      fitness_discipline: string;
      has_leaderboard_metrics: boolean;
      has_pedaling_metrics: boolean;
      id: string;
      is_total_work_personal_record: boolean;
      metrics_type: string;
      name: string;
      peloton_id: string;
      platform: string;
      ride: PelotonWorkoutListRide;
      status: string;
      strava_id: string;
      timezone: string;
      title: any;
      total_video_buffering_seconds: number;
      total_video_watch_time_seconds: number;
      total_work: number;
      user_id: string;
      workout_type: string;
    }
  ];
};

export type PelotonWorkoutListRide = {
  class_type_ids: string[];
  content_format: string;
  content_provider: string;
  description: string;
  difficulty_estimate: number;
  difficulty_level: string;
  difficulty_rating_avg: number;
  difficulty_rating_count: number;
  duration: number;
  extra_images: any[];
  fitness_discipline: string;
  fitness_discipline_display_name: string;
  has_closed_captions: boolean;
  has_pedaling_metrics: boolean;
  home_peloton_id: string;
  id: string;
  image_url: string;
  instructor_id: string;
  is_archived: boolean;
  is_closed_caption_shown: boolean;
  is_explicit: boolean;
  is_live_in_studio_only: boolean;
  language: string;
  length: number;
  live_stream_id: string;
  live_stream_url: any;
  location: string;
  metrics: string[];
  original_air_time: number;
  overall_estimate: number;
  overall_rating_avg: number;
  overall_rating_count: number;
  pedaling_duration: number;
  pedaling_end_offset: number;
  pedaling_start_offset: number;
  rating: number;
  ride_type_id: string;
  ride_type_ids: string[];
  sample_vod_stream_url: any;
  scheduled_start_time: Date;
  series_id: string;
  sold_out: boolean;
  studio_peloton_id: string;
  title: string;
  total_in_progress_workouts: number;
  total_ratings: number;
  total_workouts: number;
  vod_stream_id: string;
  vod_stream_url: string;
  start_time: 1598290308;
};
